version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 client: 
  build: client # specify the directory of the Dockerfile
  ports:
  - "4200:80" # specify port mapping #specify ports mapping

 server: # name of the first service
  build: server # specify the directory of the Dockerfile
  ports:
  - "5200:5200" # specify port mapping #specify ports mapping
  links:
  - database # link this service to the database service
 
 database: # name of the third service
  image: mongo:4.4.6 # specify image to build container from
  ports:
  - "27017:27017" # specify port forwarding
